application: frankscomicapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /update/*.
  script: helloworld.app
  login: admin
    
- url: /.*
  script: helloworld.app


 
