application: frankscomicapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.app

- url: /update/*.
  script: helloworld.app
  login: admin